spring:
  application:
    name: api
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

jwk:
  set:
    uri: https://lus-homolog.rr.sebrae.com.br/realms/microservices-homolog/protocol/openid-connect/certs
